### PR TITLE
update ruby version and re-generate Gemfile.lock

### PR DESCRIPTION
**Pull request by Lucashuang0802**
For this: https://github.com/CocoaPods/Rainforest/issues/69

### CODE REVIEW

**Comment by Lucashuang0802** [comment]
Thanks to @keitaito, I have a similar issue when trying to bootstrap the RainForest project.

**Comment by Lucashuang0802** [comment]
hi, @segiddins. Hope this can pass faster as it's really exciting to contribute to project like this. 😃

**Comment by segiddins** [comment]
👍🏻

**Comment by Lucashuang0802** [comment]
hi @segiddins, do we have a chance to merge this? 😃

**Pull request closed without merging**
